spring.application.name=jobsystem
server.port=8585
spring.datasource.url=jdbc:postgresql://localhost:5432/job_system
spring.datasource.username=postgres
spring.datasource.password=your_new_password
spring.data.redis.host=localhost
spring.data.redis.port=6379

worker.thread.count=5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true